version: '3.8'

services:
  # MongoDB Replica Set
  mongo1:
    image: mongo:latest
    container_name: mongo1
    restart: always
    ports:
      - 27017:27017
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:latest
    container_name: mongo2
    restart: always
    ports:
      - 27018:27017
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo:latest
    container_name: mongo3
    restart: always
    ports:
      - 27019:27017
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    volumes:
      - mongo3_data:/data/db

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - rabbitmq
    environment:
      MONGO_URI: mongodb://mongo1:27017,mongo2:27018,mongo3:27019/nestjs?replicaSet=rs0
      RABBITMQ_URI: amqp://${RABBITMQ_USERNAME}:${RABBITMQ_PASSWORD}@rabbitmq:5672

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
